### ISSUE TITLE
Some uses of `:has` throw "not a valid selector"

### ISSUE THREAD

**Issue by aayla-secura** [dperini/nwsapi#123]
I found two particular use cases of the `:has` selector, which work fine in modern browsers but nwsapi throws an error:

- `div:has(>div)` results in `'>div' is not a valid selector` (so having `>` at the start of the subselector string is treated as invalid)
- `:has(div)` results in `'' is not a valid selector` (so having `:has` at the start of the selector string seems to result in it being parsed as empty)

I believe the selectors above are valid and should be supported, am I wrong?

I should say I'm using version 2.2.12

**Comment by cee-chen** [comment]
+1ing this, the following selectors also throw "not a valid selector" errors for us in Jest (works fine in browsers):

[Previous sibling](https://tobiasahlin.com/blog/previous-sibling-css-has/) selectors:

```css
&:has(+ .classA) {
  color: red;
}
```

Nested `:has`/`:is`:

```css
*:has(*:is(.classA, .classB)) + *:is(.classC, .classD) {
  color: red;
}
```
